---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- name: categories
  type: tag_list
  default: []
  label: Categories
pages:
- projects/molecular-gastronomy.md
